#### 8/16 금

### OOP

In [3]:
#연습문제1
##계좌이체 메소드 구현

class Account:
    number = '0000-000-000000'
    balance = 0
    rate = 1.0
    
    def deposit(self, money):  #입금
        self.balance += money
    def withdraw(self, money):  #출금
        self.balance -= money
    def obtain_interest(self):  #이자획득
        self.balance += self.balance*(self.rate/100)

In [4]:
class MinBalanceAccount(Account):
    def __init__(self, min_balance, num='0000-000-00000', amnt=0, rate=1.0):
        Account.__init__(self, num=num, amnt=amnt, rate=rate)
        self.minimum_balance = min_balance
        self.bonus_rate=1.0
    def withdraw(self,amnt): #인출 기능 수정
        if self.balance - amnt < self.minimum_balance:
            print('Sorry, minimum balance must be maintained')
        else:
            Account.withdraw(self, amnt)
    def obtain_interest(self):
        self.balance += (self.balance)*((self.rate+self.bonums_rate)/100.0)

In [5]:
class Account:
    number = '0000-000-000000'
    balance = 0
    rate = 1.0
    set_balance = balance
    get_balance = balance
    
    def deposit(self, money):  #입금
        self.balance += money
    def withdraw(self, money):  #출금
        self.balance -= money
    def obtain_interest(self):  #이자획득
        self.balance += self.balance*(self.rate/100)
    def transfer(self, another, amnt):
        self.get_balance -= another

In [13]:
acc1 = MinBalanceAccount(min_balance=0)

In [22]:
class Account:
    num_acc = 0
    def __init__(self, num='OOO-OOO-OOOOO', amnt=0, rate=1.0):
        self.number = num
        self.balance = amnt
        self.rate = rate
        Account.num_acc += 1# 계좌의 기능(Method)
    def deposit(self, money): #입금
        self.balance += money
    def withdraw(self, money): #인출
        self.balance -= money 
    def obtain_interest(self): #이자 획득
        self.balance += self.balance*(self.rate/100)
    def get_balance(self):
        return self.balance
    def set_balance(self, amnt):
        self.balance = amnt
    def __add__(self, another): #두 계좌 통합 기능
        new_acc=Account(amnt=self.balance+another.balance, rate=self.rate)
        return new_acc
    def transfer(self,another,amnt):
        self.withdraw(amnt)
        another.deposit(amnt)
    
class MinBalanceAccount(Account):
    def __init__(self, min_balance, num='OOOO-OOO-OOOOO', amnt=0, rate=1.0):
        Account.__init__(self, num=num, amnt=amnt, rate=rate)
        self.minimum_balance = min_balance
        self.bonus_rate = 1.0
    def withdraw(self, amnt): # 인출 기능 수정
        if self.balance - amnt < self.minimum_balance:
            print('Sorry, minimum balance must be maintained')
        else:
            Account.withdraw(self, amnt)
    def obtain_interest(self): #보너스 이율 반영
        self.balance += (self.balance)*((self.rate+self.bonus_rate)/100.0)
        
    def transfer(self, another, amnt):
        self.balance -= another

In [23]:
acc1.transfer(acc2,100)

AttributeError: 'MinBalanceAccount' object has no attribute 'transfer'

### Numpy

In [25]:
import numpy as np

In [26]:
a = np.array([1,2,3]) #1차원 array [1,2,3] 생성

In [27]:
print(type(a))

<class 'numpy.ndarray'>


In [28]:
print(a.shape)

(3,)


In [29]:
print(a[0],a[1],a[2])

1 2 3


In [30]:
a[0]=5
print(a)

[5 2 3]


In [31]:
b =np.array([[1,2,3],[4,5,6]])
print(b.shape)

(2, 3)


In [32]:
print(b[0,0],b[0,1],b[0,2])

1 2 3


In [34]:
a = np.zeros((2,2))
print(a)

[[0. 0.]
 [0. 0.]]


In [36]:
b=np.ones((1,2))
print(b)

[[1. 1.]]


In [37]:
c=np.full((2,2), 7)
print(c)

[[7 7]
 [7 7]]


In [39]:
d=np.eye(2)
print(d)

[[1. 0.]
 [0. 1.]]


In [41]:
e=np.random.random((2,2)) #0~1 랜덤 값을 가지는 2*2 array생성
print(e)

[[0.65480439 0.97515268]
 [0.79242626 0.91731437]]


In [43]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a[0,1])

2


In [44]:
b=a[:2,1:3]
print(b)

[[2 3]
 [6 7]]


In [45]:
b[0,0] =7
print(a[0,1])

7


In [73]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

row_r1 = a[1,:] #1차원 행렬 (4,)
row_r2 = a[1:2, :] #2차원 행렬 (1x4) - 기존 차원 유지
print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)


In [75]:
#두번째 열의 값들을 모두 가져오는 두가지 방법
col_r1 = a[:,1]
col_r2 = a[:,1:2]
print(col_r1, col_r1.shape)
print(col_r2, col_r2.shape)

[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


In [77]:
a = np.array([[1,2],[3,4],[5,6]])
print(a)
print()
#[1 4 5] 1차원행렬 (3,) 을 얻는 두 가지 방법
print(a[[0,1,2], [0,1,0]])
print(np.array([a[0,0],a[1,1],a[2,0]]))

[[1 2]
 [3 4]
 [5 6]]

[1 4 5]
[1 4 5]


In [78]:
#[2,2] 1차원행렬 (2,)을 얻는 두 가지 방법
print(a[[0,0],[1,1]])
print(np.array([a[0,1],a[0,1]]))

[2 2]
[2 2]


In [80]:
#2차원 배열 (4x3)생성
a=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(a)
print()
b= np.array([0,2,0,1])
#arange : numpy 의 range 라고 생각!
print(a[np.arange(4), b]) #[1 6 7 11]
print()
a[np.arange(4), b] += 10

print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

[ 1  6  7 11]

[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


In [81]:
x = np.array([1,2])
print(x.dtype)

int64


In [82]:
x = np.array([1.0,2.0])
print(x.dtype)

float64


In [83]:
x = np.array([1,2], dtype=np.int64) #데이터타입 명시
print(x.dtype)

int64


In [85]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

print(x+y)
print()
print(np.add(x,y))
print()

print(x-y)
print()
print(np.subtract(x,y))

[[ 6.  8.]
 [10. 12.]]

[[ 6.  8.]
 [10. 12.]]

[[-4. -4.]
 [-4. -4.]]

[[-4. -4.]
 [-4. -4.]]


In [86]:
v = np.array([9,10])
w = np.array([11,12])

#v*w = 219
print(v.dot(w))
print(np.dot(v,w))
print()

#매트릭스/벡터곱; [29 67]
print(x.dot(v))
print(np.dot(x,v))
print()

#매트릭스/매트릭스곱;
print(x.dot(y))
print(np.dot(x,y))

219
219

[29. 67.]
[29. 67.]

[[19. 22.]
 [43. 50.]]
[[19. 22.]
 [43. 50.]]


In [89]:
x = np.array([[1,2],[3,4]])

print(np.sum(x))
print(np.sum(x, axis=0)) #각 열의 합
print(np.sum(x, axis=1)) #각 행의 합

10
[4 6]
[3 7]


In [90]:
print(x)
print(x.T) #전치행렬

v= np.array([1,2,3])
print(v)
print(v.T)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[1 2 3]
[1 2 3]


In [91]:
x = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
v = np.array([1,0,1])
y = np.empty_like(x) #x와 같은 shape의 빈 매트릭스 만들기

#x의 각 행에 v와 elementwise 합을 하여 y의 해당 행에 할당
for i in range(4):
    y[i,:] = x[i,:]+v
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [92]:
vv = np.tile(v,(4,1)) #v 내용을 4x1의 각 행에 반복함

print(vv)

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]


In [93]:
y = x+vv
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [94]:
y = x+v
print(y) #위의 vv와 같은 결과!

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [96]:
#추가적으로 reshape : 기존의 shape 을 바꿔준다
print(v.shape)
print()
v_rshp = v.reshape((1,-1))
print(v_rshp.shape)

print(x+v_rshp) #연산가능!

(3,)

(1, 3)
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [99]:
#연습문제2
##연립 2차 방정식 풀기

m1 = np.array([[1,1],[2,1]])
m2 = np.array([15,25])
m1_inv = np.linalg.inv(m1)
print(np.dot(m1_inv,m2))

[10.  5.]


# ================================
## 선정아 클래스 공부하자 ?

In [60]:
#계좌의 기능 입금, 인출, 이자획득

class Account :
    number = '0000-000-000000'
    balance = 0
    rate = 1.0
    
    #입금
    def deposit(self,money):
        self.balance += money
    #인출
    def withdraw(self,money):
        self.balance -= money
    #이자획득
    def obtain_interest(self):
        self.balance += self.balance*(self.rate/100)

In [100]:
acc1 =Account()
acc2 =Account()
acc3 =Account()

In [102]:
acc2.deposit(7000)

In [103]:
acc2.balance

7000.0

In [104]:
acc2.obtain_interest()
acc2.balance

7070.0