In [1]:
import numpy as np
from scipy import stats
import pandas as pd
import statsmodels.api as sm
import matplotlib.pyplot as pit
import seaborn as sns
from statsmodels.stats.proportion import proportions_ztest

## 추론통계
### 1. 모평균 신뢰구간 추정
#### 연습
새로운 품종의 배추 40통을 랜덤추출하여 무게를 측정. 모표준편차는 0.397, 평균 무게에 대한 95%신뢰구간을 구하시오.

In [21]:
#EXH_QC.csv 에서 읽어옴
ds_example = pd.read_csv("/home/pirl/Downloads/data/EXH_QC.csv")
df = ds_example[['Cabbage weight']].copy()

#정규분포 구간 추정 함수 실행
lower,upper = stats.norm.interval(0.95, loc=2.7, scale=0.397/np.sqrt(40))
#lower,upper = stats.norm.interval(0.95, loc=df.mean(), scale=stats.sem(df)) 도 해보기
print("신뢰구간:({0},{1})".format(lower.round(2), upper.round(2)))

신뢰구간:(2.58,2.82)


In [20]:
df.mean()

Cabbage weight    2.695
dtype: float64

#### 실습
감자 20박스를 랜덤추출하여 무게를 측정. 모표준편차는 3.8, 평균 무게에 대한 95%신뢰구간을 구하시오.

In [34]:
df = pd.DataFrame({'Sample' : [18, 18, 20, 21, 20, 23, 19, 18, 17, 21,
                               22, 20, 20, 21, 20, 19, 19, 18, 17, 19]})

In [35]:
df

Sample
0       18
1       18
2       20
3       21
4       20
5       23
6       19
7       18
8       17
9       21
10      22
11      20
12      20
13      21
14      20
15      19
16      19
17      18
18      17
19      19

In [37]:
#s/sqrt(n)

lower,upper = stats.norm.interval(0.95, loc=np.mean(df), scale=stats.sem(df))
print("신뢰구간:({0},{1})".format(lower.round(2), upper.round(2)))

신뢰구간:([18.8],[20.2])


In [29]:
#sigma(:모표준편차)/sqrt(n)

lower,upper = stats.norm.interval(0.95, loc=np.mean(df), scale=3.8/np.sqrt(20))
print("신뢰구간:({0},{1})".format(lower.round(2), upper.round(2)))

신뢰구간:([17.83],[21.17])


In [33]:
lower,upper = stats.norm.interval(0.95, loc=np.mean(df), scale=np.std(df))
print("신뢰구간:({0},{1})".format(lower.round(2), upper.round(2)))

신뢰구간:([16.43],[22.57])


#### 연습
강종의 평균 인장강도를 55kg/mm^2으로 기대하고 있음. 이를 검증하기 위해 임의로 20개의 코일을 대상으로 랜덤하게 채취. 이 모평균값의 95%신뢰구간을 추정하시오.

In [39]:
df = pd.DataFrame({'sample': [54.1, 53.3, 56.1, 55.7, 54.0, 54.1, 54.5, 57.1, 55.2, 53.8,
                             54.1, 54.1, 56.1, 55.0, 55.9, 56.0, 54.9, 54.3, 53.9, 55.0]})

lower,upper = stats.t.interval(0.95, len(df)-1, loc=np.mean(df), scale=stats.sem(df))
print("신뢰구간:({0},{1})".format(lower.round(2), upper.round(2)))

신뢰구간:([54.39],[55.33])


### 2. 가설검정
#### 연습 (1-sample t-test)
고객서비스센터의 고객만족도 평균은 76.7이다. 개선활동을 완료한 후 다음과 같은 10개의 고객만족도 데이터를 얻었다. 개선활동이 만족도를 변화시켰는가?

In [42]:
df = pd.DataFrame({'sample': [74.5, 81.2, 73.8, 82.0, 76.3, 75.7, 80.2, 72.6, 77.9, 82.8]})

t_result = stats.ttest_1samp(df,76.7)
t,p = t_result.statistic.round(3), t_result.pvalue.round(3)
print("1-sample t-test")
print("t검정통계량 :{}".format(t))
print("p-value :{}".format(p))

1-sample t-test
t검정통계량 :[0.864]
p-value :[0.41]


#### 연습 (2-sample t-test)
제품을 A공급자와 B공급자로 부터 제품을 받아 두께를 측정한 데이터이다. 공급자 간에 모평균에 차이가 있다고 할 수 있을까?

In [47]:
df1 = pd.DataFrame({'A': [1.883, 1.715, 1.799, 1.768, 1.711, 1.832, 1.427, 1.344]})
df2 = pd.DataFrame({'B': [1.435, 1.572, 1.486, 1.511, 1.457, 1.548, 1.404, 1.883]})

t_result = stats.ttest_ind(df1, df2, equal_var = True) #equal_var지정안하면 True!

t,p = t_result.statistic.round(3), t_result.pvalue.round(3)

print("2-Sample t-test")
print("t검정통계량:{}".format(t))
print("p-value:{}",format(p))

2-Sample t-test
t검정통계량:[1.7]
p-value:{} [0.111]


#### 연습 (paired t-test)
회사원 10명에 대해 영어점수가 학원가기 전의 점수와 학원수강 후에 영어점수가 짝을 이루고 있다. 회사원들의 성적은 학원가기 전후에 대해 차이가 있는지 검정하라.

In [49]:
df1 = pd.DataFrame({'before': [720, 589, 780, 648, 720, 589, 780, 648, 780, 648]})
df2 = pd.DataFrame({'after': [810, 670, 790, 712, 810, 670, 790, 712, 790, 712]})

t_result = stats.ttest_rel(df1, df2)

t,p = t_result.statistic.round(3), t_result.pvalue.round(3)

print("Paired t-test")
print("t검정통계량:{}".format(t))
print("p-value:{}",format(p))

Paired t-test
t검정통계량:[-5.324]
p-value:{} [0.]


#### 연습 (ANOVA)
posco 그룹별 직원들의 토익성적에 차이가 있는지를 알고 싶다. 각 그룹별 토익 점수의 차이 여부를 검정하여라.

In [50]:
df1 = pd.DataFrame({'A': [892, 623, 721, 678, 723, 790, 720, 670, 690, 771]})
df2 = pd.DataFrame({'B': [721, 821, 910, 678, 723, 790, 711, 790, 745, 891]})
df3 = pd.DataFrame({'C': [621, 915, 888, 721, 894, 834, 841, 912, 845, 889]})
f_result = stats.f_oneway(df1, df2,df3)

f,p = f_result.statistic.round(3), f_result.pvalue.round(3)

print("One-way ANOVA")
print("F검정통계량:{}".format(f))
print("p-value:{}",format(p))

One-way ANOVA
F검정통계량:[4.263]
p-value:{} [0.025]


In [53]:
df11 = pd.DataFrame({'A': [892, 623, 721, 678, 723, 790, 720, 670, 690, 771]})
df21 = pd.DataFrame({'B': [721, 821, 910, 678, 723, 790, 711, 790, 745, 891]})

t_result = stats.ttest_ind(df11, df21)

t,p = t_result.statistic.round(3), t_result.pvalue.round(3)

print("2-Sample t-test")
print("t검정통계량:{}".format(t))
print("p-value:{}",format(p))

2-Sample t-test
t검정통계량:[-1.468]
p-value:{} [0.159]


In [54]:
df12 = pd.DataFrame({'A': [892, 623, 721, 678, 723, 790, 720, 670, 690, 771]})
df32 = pd.DataFrame({'C': [621, 915, 888, 721, 894, 834, 841, 912, 845, 889]})

t_result = stats.ttest_ind(df12, df32)

t,p = t_result.statistic.round(3), t_result.pvalue.round(3)

print("2-Sample t-test")
print("t검정통계량:{}".format(t))
print("p-value:{}",format(p))

#p-value : 0.011 로 유의수준 0.05보다 작기때문에 귀무가설을 기각한다.
#즉, A그룹과 C그룹사이의 평균에 차이가 있다.

2-Sample t-test
t검정통계량:[-2.831]
p-value:{} [0.011]


In [55]:
df23 = pd.DataFrame({'B': [721, 821, 910, 678, 723, 790, 711, 790, 745, 891]})
df33 = pd.DataFrame({'C': [621, 915, 888, 721, 894, 834, 841, 912, 845, 889]})

t_result = stats.ttest_ind(df23, df33)

t,p = t_result.statistic.round(3), t_result.pvalue.round(3)

print("2-Sample t-test")
print("t검정통계량:{}".format(t))
print("p-value:{}",format(p))

2-Sample t-test
t검정통계량:[-1.5]
p-value:{} [0.151]


#### 연습 (1 proportion test)
고급강 제품을 가공하는 국내 고객사는 전체 중에 10% 정도가 만족. 한 해 동안 품질에 대해 노력을 하였고 전체고객 중 100여 개의 업체를 표본으로 하여 가공품질을 확인한 후 15개의 업체가 만족을 표현했다. 과연 품질개선을 한 결과로 기존보다 전체 고객 중 만족도의 차이가 있는 것인가?

In [61]:
from statsmodels.stats.proportion import proportions_ztest

count=15
nobs=100 #표본 수를 늘려도 보자!
value=.1

stat, pval = proportions_ztest(count, nobs, value)

print("1 Proportion test")
print('p검정통계량 :{0:0.3f}'.format(stat))
print('p-value: {0:0.3f}',format(pval))

1 Proportion test
p검정통계량 :1.400
p-value: {0:0.3f} 0.16142946236708322


#### 연습 (2 proportion test)
동일한 제품을 생산하는 두 공장에서 불량률을 측정한 결과이다. 두 공정의 불량률이 같다고 할 수 있는가?

In [59]:
count=np.array([4,1])
nobs=np.array([1000,1200])

stat, pval = proportions_ztest(count,nobs)

print("2 Proportion test")
print('p통계량 :{0:0.3f}'.format(stat))
print('p-value :{0:0.3f}'.format(pval))

2 Proportion test
p통계량 :1.553
p-value :0.120


#### 연습 (카이제곱 검정)
근무조별로 철강제품을 생산하고 있는데, 생산 제품의 규격이 3가지 종류가 있다. 근무조별로 제품을 생산하는 부하는 차이가 있겠는가?

In [65]:
df = pd.DataFrame({'HSG':[270, 260, 236, 234], 'SS':[228, 285, 225, 262],
                   'SPA':[277, 284, 231, 208]})

chi, pval, dof, expected = stats.chi2_contingency(df.T)

print("chi-square test")
print('chisq: {0:0.3f}'.format(chi))
print('p-value: {0:0.3f}'.format(pval))
print('degree of freedom: {}'.format(dof))
print('expected value:\n{}'.format(expected.round(3)))

chi-square test
chisq: 13.366
p-value: 0.038
degree of freedom: 6
expected value:
[[258.333 276.333 230.667 234.667]
 [258.333 276.333 230.667 234.667]
 [258.333 276.333 230.667 234.667]]


### 2. 상관분석
#### 연습
부품수리시간과 부품 수 간에 관계를 분석하기 위한 상관분석 실시

In [71]:
df1 = [1,2,3,4,4,5,6,6,7,8]
df2 = [23,29,49,64,74,87,96,97,109,119]

corr,pval = stats.pearsonr(df1, df2)

print("Correlation Analysis")
print('corr: {0:0.3f}'.format(corr))
print('p-value:{0:0.3f}'.format(pval))

Correlation Analysis
corr: 0.989
p-value:0.000


### 3. 회귀분석
#### 연습
부품수리시간과 부품 수 간에 관계를 분석하기 위한 회귀분석 실시

In [75]:
#데이터 선언
MINUTES = [1,2,3,4,4,5,6,6,7,8]
UNITS = [23,29,49,64,74,87,96,97,109,119]

#Simple Linear Regression
MINUTES = sm.add_constant(MINUTES)
model = sm.OLS(UNITS, MINUTES)
result = model.fit()

#Simple Linear Regression 결과 출력
print(result.summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.979
Model:                            OLS   Adj. R-squared:                  0.976
Method:                 Least Squares   F-statistic:                     365.3
Date:                Fri, 12 Jul 2019   Prob (F-statistic):           5.82e-08
Time:                        13:51:09   Log-Likelihood:                -29.401
No. Observations:                  10   AIC:                             62.80
Df Residuals:                       8   BIC:                             63.41
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          7.1712      3.886      1.845      0.1

/home/pirl/anaconda3/lib/python3.7/site-packages/scipy/stats/stats.py:1416: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=10
  "anyway, n=%i" % int(n))
